build:
  build_starting:
    image: python:2
    commands:
      - curl https://api.ciscospark.com/v1/messages -X POST -H "Authorization:Bearer $$SPARK_TOKEN" --data "roomId=$$SPARK_ROOM" --data "text=Drone kicking off $$APP_NAME build $CI_BUILD_NUMBER"


publish:
  docker:
    repo: $$DOCKER_ORG/$$DOCKER_REPO
    tag: "$${BRANCH##feature/}"
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL


  docker:
    repo: $$DOCKER_ORG/$$DOCKER_REPO
    tag: "latest"
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    when:
      branch: "master"


deploy:
  webhook:
    image: plugins/drone-webhook
    skip_verify: true
    method: POST
    auth:
      username: $$MANTL_USERNAME
      password: $$MANTL_PASSWORD
    urls:
      - https://$$MANTL_CONTROL/marathon/v2/apps/$$PROD_APP_NAME/restart?force=true
    when:
      branch: "master"


deploy:
  webhook:
    image: plugins/drone-webhook
    skip_verify: true
    method: POST
    auth:
      username: $$MANTL_USERNAME
      password: $$MANTL_PASSWORD
    urls:
      - https://$$MANTL_CONTROL/marathon/v2/apps/$$DEV_APP_NAME/restart?force=true
    when:
      branch: "dev"

notify:
  webhook:
    debug: true
    image: plugins/drone-webhook
    when:
      success: true
      failure: true
    method: POST
    header:
      Content-type: application/json; charset=utf-8
      Authorization: Bearer $$SPARK_TOKEN
    urls:
      - https://api.ciscospark.com/v1/messages
    template: |
      {
        "roomId": "$$SPARK_ROOM",
        {{#success build.status}}
        "text": "Drone confirms {{repo.full_name}} build {{build.number}} completed successfully.\nhttp://github.com/{{repo.full_name}}/commit/{{build.commit}}."
        {{else}}
        "text": "Drone blames {{build.author}} for breaking build {{build.number}}.\nhttp://github.com/{{repo.full_name}}/commit/{{build.commit}}."
        {{/success}}
      }
